[package]
name = "RustBoi"
version = "0.1.0"
edition = "2024"


[lib]
name = "gameboy_emu"
crate-type = ["cdylib"]

[[bin]]
name = "gameboy_emu"
path = "src/main.rs"

[dependencies]
libretro-rs = "0.1"
